name: CI

on:
  push:
    branches:
    - 'master'

jobs:
  dump:
    runs-on: ubuntu-16.04
    steps:
      - name: Deploy to Staging
        run: echo Deploy to Staging
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
