name: CI

on:
  create:
    tags:
      - 'refs/tags/*'

jobs:
  deploy_to_production:
    runs-on: ubuntu-16.04
    steps:
      - name: Deploy to Production
        run: echo Deploy to Production
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
