name: CI

on: tag
    
jobs:
  dump:
    runs-on: ubuntu-16.04
    steps:
      - name: Deploy to Production
        run: echo Deploy to Production
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
