name: CI

on:
  delete:
    branches:
    - 'refs/heads/*'
    - '!refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "\$GITHUB_REF=$GITHUB_REF"
      env:
        GITHUB_REF: ${{ github.ref }}
      