name: CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      if: startsWith(github.ref, 'refs/tags/')
    - name: Create GitHub Release
      needs: checkout
      uses: smarkup/Github-Release-Action@master
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: ${{ github.actor }}
        GITHUB_REF: ${{ github.ref }}
        RELEASE_ASSET_PATH: README.md.zip
