name: CI

on:
  create: [:branches]

jobs:
  review_start:
    runs-on: ubuntu-16.04
    steps:
      - name: Review Start
        run: echo Review Start
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
