name: CI

on:
  delete:
    branches:
    - '!master'

jobs:
  dump:
    runs-on: ubuntu-16.04
    steps:
      - name: Review Stop
        run: echo Review Stop
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
