name: CI

on:
  push:
    branches:
      - 'refs/heads/*'
      - '!master'

jobs:
  review_update:
    runs-on: ubuntu-16.04
    steps:
      - name: Review Update
        run: echo Review Update
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
